import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Button } from '../components/basic/Button'
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>CryptoHunter</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Button >Toggle Dark Mode</Button>

    </>
  )
}

export default Home
