import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import { useEffect } from 'react'
import { Anchor } from '../components/basic/Anchor'
import { Button } from '../components/basic/Button'
import CoinRow from '../components/own/CoinRow'
import CoinTable from '../components/own/CoinTable'
import Criptocurrencie from '../util/classes/Cryptocurrency'
import { getTop10ByPrice, streamSource, subscribeToStreamOf, unsuscribeToStreamOf } from '../util/data/criptocurrencies'
import { CryptocurrenciesServiceImp } from '../services/CryptocurrenciesServiceImp'
import { CryptocurrenciesService } from '../services/CryptocurrenciesService'

const cryptocurrencyService = CryptocurrenciesServiceImp.getInstance()

type props = {
  top10Coins: string
}

const Home = ({ top10Coins }: props) => {

  useEffect(() => {
    const top10CoinsSymbols = JSON.parse(top10Coins).map(({ symbol }: Criptocurrencie) => symbol)
    streamSource!.onopen == null ? streamSource!.onopen = () => subscribeToStreamOf(top10CoinsSymbols) : subscribeToStreamOf(top10CoinsSymbols)
    return () => unsuscribeToStreamOf(top10CoinsSymbols)
  })

  return (
    <>
      <main>
        <Head>
          <title>CryptoHunter</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <section className='landing  relative h-screen' >
          <h1 className='z-10'>hola</h1>

          <style jsx>{`
            .landing::before{
              
              position: absolute;
              top: 0;
              left: 0;
              height: 100%;
              width: 100%;
              content: "";
              background-image: url("/bitcoin.jpg");
              background-size: 100%;
              filter: brightness(50%);
            }
            `}</style>
        </section>
        <section>
          <h2 className='my-8 text-2xl font-bold tracking-wider'>Best Priced (Last 24H)</h2>
          <CoinTable coins={JSON.parse(top10Coins)} />
          <div className='flex justify-center items-center py-6'>
            <Anchor href='/markets'>View all criptocurrencies</Anchor>
          </div>

        </section >


      </main>

    </>
  )
}

export default Home

export const getStaticProps: GetStaticProps = async (context) => {
  const top10Coins = await getTop10ByPrice()
  console.log(top10Coins)
  return {
    props: {
      top10Coins
    }
  }
}
